name = "sub-api-generator"
# Pages Advanced Mode uses _worker.js from this directory as the Functions entry.
pages_build_output_dir = "."
compatibility_date = "2026-06-15"

[[kv_namespaces]]
binding = "KV"
id = "2bd991e430a34cc597cc437d50ec1eb5"
preview_id = "59c0f629c30b44059a42b12417823d8e"
